# Generated by Django 4.1.7 on 2023-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='calendar_id',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
