# Generated by Django 4.1.7 on 2023-03-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_calendarevent_calendar_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
